name: CD

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Pegar o cache do build anterior
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      # Aqui você pode adicionar qualquer outra etapa necessária antes de seguir com o build em outro arquivo

      # Se o build é feito em outro arquivo, então basta chamar o arquivo de build, como por exemplo:
      # - name: Executar build em outro arquivo
        # run: bash ./outro-arquivo-de-build.sh
