name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Usar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Instalar pnpm
      run: npm install -g pnpm
    - name: Instalar dependências
      run: pnpm install --frozen-lockfile
    - name: Build
      run: pnpm run build
